Ajout de fonctionnalité dans master par cherry-pick
BobbySoftwares/Bybbot pull request #30
Opened 2022-05-19 19:41 UTC by GlitchiKun

- Ajout des slash-commands pour le swag et les €agnottes
- Ajout du clean automatique de la $wagchain des StyleGenerationBlock
- Ajout de l'ajout du canal de log
- Ajout du Backup de la swagchain

2022-05-23 09:42 UTC, gggto requested changes
My job here is done

2022-05-23 09:42 UTC, gggto commented on pyproject.toml
> -PyNaCl = "^1.5.0"
Is that normal? I think so but can't remember why

2022-05-23 09:42 UTC, gggto commented on swag/blockchain/synced_blockchain.py
> +        print(f"Delation of {block}")
Deletion

2022-05-23 09:42 UTC, gggto commented on swag/blockchain/synced_blockchain.py
> +            unstructured_blocks.append(json.loads(message.content))
Why are you retrieving the distant blockchain instead of just dumping the local one?

2022-05-23 09:42 UTC, gggto commented on swag/blockchain/blockchain.py
> +        old_style_gen_block = [block for block in self._chain if isinstance(block,StyleGeneration) and block.timestamp.datetime < oldest_blocking_date]
You don't need to build the list, you can expand it in the for loop below

2022-05-23 09:42 UTC, gggto commented on swag/blockchain/blockchain.py
> +            oldest_blocking_date = min([user_account.blocking_date for user_account in self._accounts.users.values() if user_account.blocking_date != None])
You don't need to put the [], and you should write `is not None`

2022-05-23 09:42 UTC, gggto commented on swag/blocks/cagnotte_blocks.py
> +    def _user_id_default(self):
We do not need to maintain retro compatibility on these ones do we?

2022-05-23 09:42 UTC, gggto commented on swag/blocks/cagnotte_blocks.py
> +    def _user_id_default(self):
Same remark

2022-05-23 09:42 UTC, gggto commented on swag/blocks/swag_blocks.py
> +        if type(self.giver_id) == CagnotteId:
Type() is, not ==

2022-05-23 09:42 UTC, gggto commented on swag/blocks/swag_blocks.py
> +            if self.issuer_id not in db._accounts[self.giver_id].managers:
Oh boy, we are in trouble

Ok, so

This means we cannot delegate a cagnotte transaction

I'm starting to wonder, if, actually, we maybe should remove the user_id from the cagnotte related block and say "Ok, permissions on accounts cannot be transitives, therefore a cagnotte manager cannot grant implicit cagnotte management through its own account, therefore only issuer_id should be checked against permissions"

2022-05-23 09:42 UTC, gggto commented on swag/currencies.py
> +    _CURRENCY = None
There's a way to mark this constant as abstract with a decorator from the abc module

2022-05-23 09:42 UTC, gggto commented on swag/currencies.py
> +    def get_class(cls,currency_str):
Actually this doesn't need to be in a class

2022-05-23 09:42 UTC, gggto commented on swag/client/cagnotte.py
> +    async def cagnotte_id_autocomplete_manager(
autocomplete_managed_cagnotte_id ?

2022-05-23 09:42 UTC, gggto commented on swag/client/cagnotte.py
> +    async def cagnotte_id_autocomplete(
autocomplete_cagnotte_id ?

2022-05-23 09:42 UTC, gggto commented on swag/client/cagnotte.py
> +            if user_input in cagnotte_id[0].id
Smart, but at some point a real fuzzy searcher would be fantastic

2022-05-24 13:32 UTC, GlitchiKun commented on swag/blockchain/synced_blockchain.py
> +        print(f"Delation of {block}")
No.

Because those blocks are deemed despicable and shameful.

*tousse*

Ofc it's Deletion

2022-05-24 13:32 UTC, GlitchiKun commented on swag/blockchain/synced_blockchain.py
> +            unstructured_blocks.append(json.loads(message.content))
Because this idea didn't cross my mind, but it's a good one, I will fix it.

2022-07-24 13:55 UTC, merged